[versions]
agp = "9.4.1"
kotlin = "2.2.10"

compileSdk = "37"
minSdk = "23"
targetSdk = "36"

jvm = "17"

activityCompose = "1.12.4"
composeBom = "2026.09.00"
lifecycle = "2.10.0"
material = "1.13.0"
opentelemetry = "1.4.0-alpha"
junit4 = "4.13.2"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
opentelemetry-android-agent = { module = "io.opentelemetry.android:android-agent" }
opentelemetry-android-bom = { module = "io.opentelemetry.android:opentelemetry-android-bom", version.ref = "opentelemetry" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

odyctivity-android-application = { id = "odyctivity.android.application" }
odyctivity-android-compose = { id = "odyctivity.android.compose" }
odyctivity-android-library = { id = "odyctivity.android.library" }
